### ISSUE TITLE
La estructura de tu repositorio no cumple con lo solicitado

### ISSUE THREAD

**Issue by Juan-Insa** [FedericoSlavinchins/EstrD2023s1#1]
Es importante que aprendan a respetar las consignas al pie de la letra. La entrega 1 tiene que estar en tp-1/tp-1.hs, y así con el resto.

**Comment by FedericoSlavinchins** [comment]
Solucionado. Pido disculpas si la estructura no es la correcta, tengo un problema acerca de que no me deja visualizar el video donde se explica git y github en el link del drive subido al campus. Yo ya tenia git instalado anteriormente y conectado a mi cuenta en la computadora, pero quería avisar nada mas que no me carga el video y es por eso que pasé por alto lo de la estructura que se acordó para el repo. Ya lo arreglé, en caso de que tenga que modificarlo nuevamente lo hago. Gracias

**Comment by FedericoSlavinchins** [comment]
Y perdón que cerré el issue sin querer, ya lo volví a abrir!
