### ISSUE TITLE
Pr.1: Hay paréntesis de más en la función crecer

### ISSUE THREAD

**Issue by Juan-Insa** [FedericoSlavinchins/EstrD2023s1#5]
No hace falta poner entre paréntesis al constructor de Persona con sus parámetros del lado derecho del = (donde se construyen los datos).
Lo mismo pasa en cambioDeNombre

**Comment by FedericoSlavinchins** [comment]
Solucionado. Se removieron los paréntesis innecesarios en ambas funciones.
